"""Markdown report exporter."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from scorerift.grades import score_to_grade

if TYPE_CHECKING:
    from scorerift.engine import AuditEngine


def export_markdown(engine: AuditEngine, path: str | Path | None = None) -> str:
    """Export latest scores as a Markdown report.

    If path is given, writes to file. Always returns the Markdown string.
    """
    scores = engine.latest_scores()
    health = engine.health_check()
    lines: list[str] = []

    lines.append(f"# Audit Report — {health['grade']} ({health['score']:.3f})")
    lines.append("")

    if health["failing"]:
        lines.append(f"**Failing dimensions:** {', '.join(health['failing'])}")
    if health["divergences"]:
        lines.append(f"**Active divergences:** {health['divergences']}")
    lines.append("")

    # Score table
    lines.append("| Dimension | Auto | Grade | Manual | Status | Confidence |")
    lines.append("|-----------|------|-------|--------|--------|------------|")

    for s in scores:
        auto_grade = score_to_grade(s.auto_score)
        manual = s.manual_grade or "—"
        status = "diverged" if s.divergent else "ok"
        if s.acknowledged:
            status = "ack"
        conf = f"{s.auto_confidence:.0%}"
        lines.append(
            f"| {s.name} | {s.auto_score:.3f} | {auto_grade} | {manual} | {status} | {conf} |"
        )

    lines.append("")
    lines.append("*Generated by scorerift*")
    lines.append("")

    output = "\n".join(lines)
    if path:
        Path(path).write_text(output, encoding="utf-8")
    return output
